### ISSUE TITLE
ZIP error on OSX - Quarantine folders

### ISSUE THREAD

**Issue by JulienRamel** [sindresorhus/gulp-zip#68]
Hi,

I generated a ZIP with gulp-zip on Windows and then tried to open it with native unarchiver on OSX. I got an "Error 1 - Operation not permitted". The file can be open on Windows and on Linux & OSX with the "unzip" command line. Also, the file can be open with an alternative application on OSX (The Unarchiver).

After some investigations, I discovered the extracted folder could not be deleted from OSX Finder. So I tried to delete it from command line, and could only delete some sub-files and sub-folder, but not 2 specific folders.

I tried to use `ls -@l` command to display extended attribute keys of these folders, and this was the result :

![Issue](http://woodgate.fr/bazard/screenshot_492.jpg)

The folders "img" and "css" were put in quarantine by OSX !
Do you know if it could be linked to gulp-zip ?

Thanks for your help.

Julien

**Comment by vovayatsyuk** [comment]
It seems, that it's a standard Mac behaviour for archives downloaded with safari or chrome.

Maybe this link will help you: http://apple.stackexchange.com/a/104875

**Comment by nk-o** [comment]
Hey, @sindresorhus.

I also got this error. When I zipped my folder using gulp-zip on Windows, I can't extract it with default finder in Mac OS and got error "Error 1 - Operation not permitted".
But when I zipped this folder using TotalCommander, on Mac OX it is extracted with no problems.

So, I think the problem is not on Mac OS side, but on gulp-zip or dependencies.
